GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGF2aWQiLCJpYXQiOjE2MTgwODU2NzcsImV4cCI6MTYxODA4NTY5Mn0.x1Iv9kIdUDwBIUwtwWp7QsA8QDp_BVA089o4t7QlzPE

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGF2aWQiLCJpYXQiOjE2MTgwODY3MTZ9.1mtfOqgp7vbbdyHvV0WNkpPtsPjdgfabWxWkI_iU9qA"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "David"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGF2aWQiLCJpYXQiOjE2MTgwODY3MTZ9.1mtfOqgp7vbbdyHvV0WNkpPtsPjdgfabWxWkI_iU9qA"
}